// Code generated by goyacc -o gram_y.go gram.y. DO NOT EDIT.

//line gram.y:7
package parser

import __yyfmt__ "fmt"

//line gram.y:7

import (
	ast "github.com/GuanceCloud/platypus/pkg/ast"
)

//line gram.y:15
type yySymType struct {
	yys      int
	aststmts ast.Stmts
	astblock *ast.BlockStmt

	ifitem *ast.IfStmtElem
	iflist []*ast.IfStmtElem
	node   *ast.Node
	nodes  []*ast.Node
	item   Item
}

const SEMICOLON = 57346
const COMMA = 57347
const COMMENT = 57348
const DOT = 57349
const EOF = 57350
const ERROR = 57351
const ID = 57352
const NUMBER = 57353
const LEFT_PAREN = 57354
const LEFT_BRACKET = 57355
const LEFT_BRACE = 57356
const RIGHT_BRACE = 57357
const RIGHT_PAREN = 57358
const RIGHT_BRACKET = 57359
const SPACE = 57360
const STRING = 57361
const QUOTED_STRING = 57362
const MULTILINE_STRING = 57363
const FOR = 57364
const IN = 57365
const WHILE = 57366
const BREAK = 57367
const CONTINUE = 57368
const RETURN = 57369
const EOL = 57370
const COLON = 57371
const STR = 57372
const INT = 57373
const FLOAT = 57374
const BOOL = 57375
const LIST = 57376
const MAP = 57377
const operatorsStart = 57378
const ADD = 57379
const DIV = 57380
const GTE = 57381
const GT = 57382
const NOT = 57383
const LT = 57384
const LTE = 57385
const MOD = 57386
const MUL = 57387
const NEQ = 57388
const EQ = 57389
const EQEQ = 57390
const SUB = 57391
const ADD_EQ = 57392
const SUB_EQ = 57393
const DIV_EQ = 57394
const MUL_EQ = 57395
const MOD_EQ = 57396
const operatorsEnd = 57397
const keywordsStart = 57398
const TRUE = 57399
const FALSE = 57400
const IDENTIFIER = 57401
const AND = 57402
const OR = 57403
const FN = 57404
const NIL = 57405
const NULL = 57406
const IF = 57407
const ELIF = 57408
const ELSE = 57409
const keywordsEnd = 57410
const startSymbolsStart = 57411
const START_STMTS = 57412
const startSymbolsEnd = 57413
const UMINUS = 57414

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SEMICOLON",
	"COMMA",
	"COMMENT",
	"DOT",
	"EOF",
	"ERROR",
	"ID",
	"NUMBER",
	"LEFT_PAREN",
	"LEFT_BRACKET",
	"LEFT_BRACE",
	"RIGHT_BRACE",
	"RIGHT_PAREN",
	"RIGHT_BRACKET",
	"SPACE",
	"STRING",
	"QUOTED_STRING",
	"MULTILINE_STRING",
	"FOR",
	"IN",
	"WHILE",
	"BREAK",
	"CONTINUE",
	"RETURN",
	"EOL",
	"COLON",
	"STR",
	"INT",
	"FLOAT",
	"BOOL",
	"LIST",
	"MAP",
	"operatorsStart",
	"ADD",
	"DIV",
	"GTE",
	"GT",
	"NOT",
	"LT",
	"LTE",
	"MOD",
	"MUL",
	"NEQ",
	"EQ",
	"EQEQ",
	"SUB",
	"ADD_EQ",
	"SUB_EQ",
	"DIV_EQ",
	"MUL_EQ",
	"MOD_EQ",
	"operatorsEnd",
	"keywordsStart",
	"TRUE",
	"FALSE",
	"IDENTIFIER",
	"AND",
	"OR",
	"FN",
	"NIL",
	"NULL",
	"IF",
	"ELIF",
	"ELSE",
	"keywordsEnd",
	"startSymbolsStart",
	"START_STMTS",
	"startSymbolsEnd",
	"UMINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line gram.y:803

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 27,
	5, 45,
	47, 45,
	-2, 40,
	-1, 30,
	13, 118,
	-2, 28,
	-1, 31,
	13, 119,
	-2, 29,
	-1, 34,
	13, 121,
	-2, 32,
	-1, 38,
	13, 120,
	-2, 36,
	-1, 79,
	5, 45,
	47, 45,
	-2, 71,
	-1, 186,
	1, 79,
	4, 79,
	8, 79,
	15, 79,
	28, 79,
	-2, 154,
	-1, 259,
	5, 45,
	47, 45,
	-2, 40,
}

const yyPrivate = 57344

const yyLast = 2175

var yyAct = [...]int16{
	79, 53, 215, 27, 41, 28, 103, 27, 27, 75,
	73, 39, 3, 68, 9, 62, 61, 66, 62, 62,
	278, 238, 254, 268, 19, 63, 172, 83, 63, 63,
	82, 77, 61, 264, 101, 62, 43, 54, 51, 64,
	102, 100, 296, 111, 46, 63, 47, 80, 104, 113,
	261, 281, 98, 101, 295, 265, 120, 121, 122, 102,
	100, 112, 55, 243, 99, 249, 57, 81, 137, 131,
	81, 81, 114, 9, 56, 130, 132, 89, 130, 135,
	2, 126, 44, 45, 127, 69, 9, 81, 48, 49,
	211, 98, 101, 90, 91, 118, 94, 95, 102, 100,
	96, 72, 97, 99, 40, 107, 106, 124, 128, 70,
	160, 106, 163, 130, 93, 167, 171, 159, 9, 162,
	174, 123, 166, 110, 8, 71, 178, 76, 108, 109,
	4, 110, 67, 105, 130, 181, 108, 109, 186, 189,
	190, 191, 192, 193, 194, 195, 196, 197, 198, 199,
	200, 201, 202, 203, 204, 205, 206, 207, 208, 210,
	103, 80, 212, 244, 209, 216, 218, 134, 184, 217,
	221, 10, 1, 18, 223, 89, 225, 227, 30, 116,
	27, 228, 6, 50, 186, 186, 130, 31, 52, 98,
	101, 90, 91, 239, 94, 95, 102, 100, 96, 32,
	97, 99, 84, 85, 87, 86, 88, 80, 80, 60,
	38, 37, 93, 92, 231, 233, 98, 101, 90, 91,
	33, 94, 95, 102, 100, 96, 59, 97, 99, 58,
	36, 229, 186, 130, 5, 130, 35, 259, 65, 245,
	130, 263, 34, 11, 17, 16, 15, 14, 270, 13,
	12, 237, 275, 213, 279, 80, 21, 130, 74, 29,
	7, 0, 255, 0, 0, 0, 0, 284, 286, 285,
	287, 217, 0, 129, 293, 294, 0, 0, 0, 0,
	0, 0, 0, 130, 0, 0, 0, 301, 0, 0,
	0, 115, 117, 306, 119, 0, 0, 0, 0, 0,
	312, 0, 0, 0, 125, 315, 317, 0, 0, 0,
	0, 321, 323, 0, 0, 326, 0, 0, 0, 0,
	0, 330, 0, 0, 138, 139, 140, 141, 142, 143,
	144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
	154, 155, 156, 157, 158, 0, 161, 0, 164, 165,
	133, 0, 0, 169, 0, 0, 0, 0, 173, 0,
	0, 0, 0, 175, 176, 0, 0, 0, 0, 0,
	0, 179, 20, 0, 0, 61, 0, 188, 62, 43,
	54, 51, 64, 177, 0, 168, 0, 46, 63, 47,
	22, 0, 0, 24, 23, 26, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 55, 180, 0, 0, 57,
	185, 0, 0, 0, 224, 0, 0, 56, 0, 0,
	0, 0, 0, 89, 0, 44, 45, 236, 9, 246,
	25, 48, 49, 42, 0, 0, 0, 98, 101, 90,
	91, 0, 94, 95, 102, 100, 96, 0, 97, 99,
	0, 240, 241, 242, 0, 0, 232, 234, 235, 247,
	93, 92, 0, 0, 0, 0, 251, 252, 253, 0,
	0, 0, 0, 0, 0, 0, 0, 260, 0, 0,
	0, 0, 0, 266, 267, 0, 269, 0, 273, 0,
	274, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 282, 0, 0, 256, 257, 0, 258, 0, 0,
	0, 292, 262, 0, 0, 0, 299, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 304, 280,
	305, 0, 0, 0, 0, 310, 0, 311, 0, 0,
	0, 0, 314, 20, 0, 0, 61, 0, 320, 62,
	43, 54, 51, 64, 0, 300, 0, 0, 46, 63,
	47, 22, 0, 0, 24, 23, 26, 66, 0, 0,
	0, 0, 0, 0, 0, 0, 55, 0, 0, 0,
	57, 0, 0, 0, 0, 0, 0, 0, 56, 0,
	0, 0, 0, 0, 0, 0, 44, 45, 0, 0,
	0, 25, 48, 49, 42, 20, 0, 0, 61, 0,
	0, 62, 43, 54, 51, 64, 0, 0, 0, 0,
	46, 63, 47, 22, 0, 0, 24, 23, 26, 9,
	0, 0, 0, 0, 0, 0, 0, 0, 55, 0,
	0, 0, 57, 0, 0, 0, 0, 0, 0, 0,
	56, 0, 0, 0, 0, 0, 0, 0, 44, 45,
	0, 0, 0, 25, 48, 49, 42, 61, 0, 0,
	62, 43, 54, 51, 64, 0, 0, 0, 0, 46,
	63, 47, 22, 0, 0, 24, 23, 26, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 55, 0, 0,
	0, 57, 0, 0, 0, 0, 0, 61, 0, 56,
	62, 43, 54, 51, 64, 0, 283, 44, 45, 46,
	63, 47, 25, 48, 49, 42, 61, 0, 0, 62,
	43, 54, 51, 64, 0, 0, 289, 55, 46, 63,
	47, 57, 0, 0, 0, 0, 0, 0, 288, 56,
	0, 0, 0, 0, 0, 0, 55, 44, 45, 0,
	57, 0, 81, 48, 49, 0, 0, 0, 56, 0,
	0, 0, 0, 0, 0, 0, 44, 45, 0, 0,
	0, 81, 48, 49, 61, 0, 0, 62, 43, 54,
	51, 64, 0, 0, 277, 0, 46, 63, 47, 0,
	0, 0, 0, 0, 0, 0, 276, 0, 0, 0,
	0, 0, 0, 0, 55, 0, 0, 0, 57, 0,
	0, 0, 0, 0, 0, 0, 56, 0, 0, 0,
	0, 0, 0, 0, 44, 45, 0, 0, 0, 81,
	48, 49, 61, 0, 0, 62, 43, 54, 51, 64,
	0, 0, 272, 0, 46, 63, 47, 0, 0, 0,
	0, 0, 0, 0, 271, 0, 0, 0, 0, 0,
	0, 0, 55, 0, 0, 61, 57, 0, 62, 43,
	54, 51, 64, 0, 56, 331, 0, 46, 63, 47,
	0, 0, 44, 45, 0, 0, 0, 81, 48, 49,
	0, 0, 0, 0, 0, 55, 0, 0, 61, 57,
	0, 62, 43, 54, 51, 64, 0, 56, 327, 0,
	46, 63, 47, 0, 0, 44, 45, 0, 0, 0,
	81, 48, 49, 0, 0, 0, 0, 0, 55, 0,
	0, 61, 57, 0, 62, 43, 54, 51, 64, 0,
	56, 324, 0, 46, 63, 47, 0, 0, 44, 45,
	0, 0, 0, 81, 48, 49, 0, 0, 0, 0,
	0, 55, 0, 0, 61, 57, 0, 62, 43, 54,
	51, 64, 0, 56, 322, 0, 46, 63, 47, 0,
	0, 44, 45, 0, 0, 0, 81, 48, 49, 0,
	0, 0, 0, 0, 55, 0, 0, 61, 57, 0,
	62, 43, 54, 51, 64, 0, 56, 318, 0, 46,
	63, 47, 0, 0, 44, 45, 0, 0, 0, 81,
	48, 49, 0, 0, 0, 0, 0, 55, 0, 0,
	61, 57, 0, 62, 43, 54, 51, 64, 0, 56,
	316, 0, 46, 63, 47, 0, 0, 44, 45, 0,
	0, 0, 81, 48, 49, 0, 0, 0, 0, 0,
	55, 0, 0, 61, 57, 0, 62, 43, 54, 51,
	64, 0, 56, 313, 0, 46, 63, 47, 0, 0,
	44, 45, 0, 0, 0, 81, 48, 49, 0, 0,
	0, 0, 0, 55, 0, 0, 61, 57, 0, 62,
	43, 54, 51, 64, 0, 56, 307, 0, 46, 63,
	47, 0, 0, 44, 45, 0, 0, 0, 81, 48,
	49, 0, 0, 0, 0, 0, 55, 0, 61, 0,
	57, 62, 43, 54, 51, 64, 0, 0, 56, 0,
	46, 63, 47, 0, 0, 0, 44, 45, 0, 0,
	226, 81, 48, 49, 0, 0, 0, 0, 55, 0,
	61, 0, 57, 62, 43, 54, 51, 64, 222, 0,
	56, 0, 46, 63, 47, 0, 0, 0, 44, 45,
	0, 0, 0, 81, 48, 49, 0, 0, 0, 0,
	55, 0, 0, 61, 57, 0, 62, 43, 54, 51,
	64, 0, 56, 220, 0, 46, 63, 47, 0, 0,
	44, 45, 0, 0, 0, 81, 48, 49, 0, 0,
	0, 0, 0, 55, 0, 61, 0, 57, 62, 43,
	54, 51, 64, 0, 0, 56, 0, 46, 63, 47,
	0, 0, 0, 44, 45, 0, 0, 219, 81, 48,
	49, 0, 0, 0, 0, 55, 0, 61, 0, 57,
	62, 43, 54, 51, 64, 0, 214, 56, 0, 46,
	63, 47, 0, 0, 0, 44, 45, 0, 0, 0,
	81, 48, 49, 0, 0, 0, 182, 55, 0, 61,
	0, 57, 62, 43, 54, 51, 64, 0, 0, 56,
	0, 46, 63, 47, 0, 0, 0, 44, 45, 0,
	0, 0, 81, 48, 49, 0, 0, 0, 0, 55,
	0, 61, 0, 57, 62, 43, 54, 51, 64, 177,
	0, 56, 0, 46, 63, 47, 0, 0, 0, 44,
	45, 0, 0, 0, 81, 48, 49, 0, 0, 0,
	0, 55, 0, 0, 61, 57, 0, 62, 43, 54,
	51, 64, 0, 56, 170, 0, 46, 63, 47, 0,
	0, 44, 45, 0, 0, 0, 81, 48, 49, 0,
	0, 0, 0, 136, 55, 0, 61, 0, 57, 62,
	43, 54, 51, 64, 0, 0, 56, 0, 46, 63,
	47, 0, 0, 0, 44, 45, 0, 0, 0, 81,
	48, 49, 0, 0, 0, 78, 55, 0, 61, 0,
	57, 62, 43, 54, 51, 64, 0, 0, 56, 0,
	46, 63, 47, 0, 0, 0, 44, 45, 0, 0,
	0, 81, 48, 49, 0, 0, 0, 0, 55, 0,
	61, 0, 57, 62, 43, 54, 51, 64, 0, 0,
	56, 0, 46, 63, 47, 0, 0, 0, 44, 45,
	0, 0, 0, 81, 48, 49, 0, 0, 0, 0,
	55, 0, 61, 0, 57, 62, 43, 54, 51, 187,
	0, 0, 56, 0, 46, 63, 47, 0, 0, 0,
	44, 45, 0, 0, 0, 81, 48, 49, 0, 0,
	0, 0, 55, 0, 0, 0, 57, 0, 0, 0,
	0, 0, 0, 0, 56, 0, 89, 0, 0, 0,
	0, 0, 44, 45, 0, 0, 0, 81, 48, 49,
	98, 101, 90, 91, 0, 94, 95, 102, 100, 96,
	0, 97, 99, 84, 85, 87, 86, 88, 0, 309,
	0, 0, 0, 93, 92, 89, 0, 0, 0, 0,
	0, 308, 0, 0, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 303,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 302, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 298,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 297, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 291,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 290, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 335,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 0, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 334,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 0, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 333,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 0, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 332,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 0, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 329,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 0, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 328,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 0, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 325,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 0, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 319,
	97, 99, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 0, 93, 92, 0, 0, 0, 0, 0, 98,
	101, 90, 91, 0, 94, 95, 102, 100, 96, 0,
	97, 99, 89, 0, 0, 0, 0, 9, 0, 0,
	0, 0, 93, 92, 0, 0, 98, 101, 90, 91,
	0, 94, 95, 102, 100, 96, 0, 97, 99, 89,
	0, 0, 0, 0, 0, 250, 0, 0, 0, 93,
	92, 0, 0, 98, 101, 90, 91, 0, 94, 95,
	102, 100, 96, 0, 97, 99, 89, 0, 0, 0,
	0, 0, 248, 0, 230, 0, 93, 92, 0, 0,
	98, 101, 90, 91, 0, 94, 95, 102, 100, 96,
	0, 97, 99, 89, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 93, 92, 0, 0, 98, 101, 90,
	91, 0, 94, 95, 102, 100, 96, 0, 97, 99,
	89, 0, 0, 0, 0, 0, 228, 0, 183, 0,
	93, 92, 0, 0, 98, 101, 90, 91, 0, 94,
	95, 102, 100, 96, 0, 97, 99, 89, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 93, 92, 0,
	0, 98, 101, 90, 91, 131, 94, 95, 102, 100,
	96, 0, 97, 99, 89, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 93, 92, 0, 0, 98, 101,
	90, 91, 0, 94, 95, 102, 100, 96, 0, 97,
	99, 89, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 93, 92, 0, 0, 98, 101, 90, 91, 0,
	94, 95, 102, 100, 96, 0, 97, 99, 89, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 93, 92,
	0, 0, 98, 101, 90, 91, 0, 94, 95, 102,
	100, 96, 0, 97, 99,
}

var yyPact = [...]int16{
	10, 122, 601, -1000, -1000, -1000, 539, 660, 81, -1000,
	97, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -57, 1421, -1000, -1000, 8, 1453, 1513, 1, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 126, -1000, 98,
	-1000, 124, 1453, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	44, -14, 90, -1000, -14, 1453, 1453, 1453, -1000, -1000,
	108, 94, -1000, -1000, -14, -1000, -1000, 81, 80, -1000,
	-1000, -1000, -1000, 55, -1000, 1453, 55, 163, 1389, 1513,
	-1000, -1000, 56, 2098, -14, -14, -14, -14, -14, -14,
	-14, -14, -14, -14, -14, -14, -14, -14, -14, -14,
	-14, -14, -14, -14, -14, 9, -14, 9, -14, -14,
	9, 2071, -1000, -14, -1000, 1357, -11, 11, -14, 1453,
	-1000, -1000, -1000, -14, -14, 1324, 80, -1000, -1000, -1000,
	-1000, -14, 2071, -1000, 1292, 2044, 1485, -14, 1453, 1453,
	1453, 1453, 1453, 1453, 1453, 1453, 1453, 1453, 1453, 1453,
	1453, 1453, 1453, 1453, 1453, 1453, 1453, 1453, 1453, 93,
	77, 1453, 93, 77, 1260, 1228, 93, 77, -1000, 1196,
	-1000, 2098, -1000, 1163, 1909, 1131, 1453, -1000, 2017, 368,
	-1000, 1990, 1485, 1485, 55, -1000, -1000, -14, 5, 2098,
	2098, 2098, 2098, 2098, 179, 15, 15, 54, 2125, 15,
	15, 15, 15, -4, -4, -1000, -1000, -1000, 2098, 155,
	2098, -14, 1909, 58, -1000, -1000, 2098, 116, 400, -14,
	-1000, 2098, -1000, 1963, 49, 1936, -14, 1909, -14, 7,
	1485, 55, -1000, 55, -1000, -1000, 368, 45, 55, -1000,
	1453, 16, 39, -14, -14, 6, -14, 835, -14, -1000,
	-14, 777, 3, 1453, -1000, 55, -1000, -1000, -1000, 152,
	35, -14, -1000, 1909, -1000, -1000, 700, 1453, -1000, 719,
	1642, -14, -1000, 1453, 25, 1612, -14, -1000, -1000, 2098,
	-1000, 55, 8, -1000, 2098, -1000, 2098, 1582, -14, -1000,
	-14, -1000, 1099, 2098, 1552, -14, -1000, -14, -1000, 1066,
	-1000, -1000, -14, -1000, 1033, 1000, 1882, -1000, -14, -1000,
	967, 934, 1852, -1000, 901, 1822, -1000, 1792, -1000, -1000,
	868, 1762, -1000, 1732, -1000, -1000, 1702, -1000, -1000, -1000,
	1672, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 273, 1, 231, 260, 259, 258, 256, 253, 5,
	251, 124, 24, 250, 249, 247, 246, 245, 244, 243,
	242, 2, 4, 236, 230, 229, 226, 220, 11, 211,
	210, 209, 104, 0, 199, 188, 187, 183, 178, 31,
	173, 172, 13, 171, 179, 239,
}

var yyR1 = [...]int8{
	0, 42, 42, 42, 42, 43, 43, 43, 41, 41,
	41, 41, 41, 3, 3, 3, 4, 4, 4, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 33, 33,
	33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
	40, 44, 44, 45, 45, 9, 9, 12, 12, 12,
	12, 12, 12, 32, 16, 15, 18, 18, 17, 17,
	10, 10, 13, 14, 14, 14, 14, 14, 14, 14,
	14, 39, 39, 19, 19, 5, 7, 7, 6, 1,
	1, 2, 20, 20, 20, 8, 8, 8, 8, 21,
	23, 23, 23, 24, 24, 25, 25, 25, 25, 25,
	25, 25, 25, 26, 26, 26, 26, 26, 27, 28,
	28, 28, 29, 29, 29, 29, 29, 29, 31, 31,
	31, 31, 30, 30, 30, 30, 30, 30, 30, 30,
	30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
	30, 30, 30, 30, 30, 30, 36, 36, 36, 37,
	37, 37, 34, 34, 34, 35, 35, 22, 22, 22,
	38, 38, 38, 38, 38, 38, 38,
}

var yyR2 = [...]int8{
	0, 1, 1, 2, 2, 1, 2, 2, 2, 2,
	3, 2, 1, 2, 1, 1, 2, 1, 3, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 1, 0, 1, 4, 4, 4, 4,
	4, 4, 4, 4, 1, 1, 1, 2, 8, 6,
	1, 4, 3, 7, 6, 6, 5, 6, 5, 5,
	4, 1, 1, 1, 3, 3, 1, 2, 3, 1,
	4, 3, 6, 7, 4, 4, 4, 1, 1, 4,
	2, 2, 2, 1, 1, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 5, 6,
	6, 6, 3, 3, 3, 3, 3, 3, 1, 1,
	1, 1, 11, 10, 10, 9, 10, 9, 9, 8,
	8, 7, 7, 6, 11, 10, 10, 9, 10, 9,
	9, 8, 8, 7, 7, 6, 2, 4, 3, 3,
	4, 2, 3, 4, 1, 6, 7, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -41, 70, 2, 8, -3, -44, -4, -11, 28,
	-43, -19, -13, -14, -15, -16, -17, -18, -40, -12,
	4, -7, 22, 26, 25, 62, 27, -33, -9, -5,
	-38, -36, -34, -27, -20, -23, -24, -29, -30, -28,
	-32, -22, 65, 11, 57, 58, 19, 21, 63, 64,
	-37, 13, -35, -2, 12, 37, 49, 41, -25, -26,
	-31, 7, 10, 20, 14, -3, 28, -11, -42, 4,
	28, 28, 4, 67, -6, 66, -32, -39, 4, -33,
	-12, 62, -22, -33, 50, 51, 53, 52, 54, 23,
	39, 40, 61, 60, 42, 43, 46, 48, 37, 49,
	45, 38, 44, 5, 47, 7, 13, 7, 12, 13,
	7, -33, 17, 5, 28, -45, -44, -45, 5, -45,
	-33, -33, -33, 13, 13, -45, -42, 4, 28, -1,
	-2, 14, -33, -1, 4, -33, 4, 12, -45, -45,
	-45, -45, -45, -45, -45, -45, -45, -45, -45, -45,
	-45, -45, -45, -45, -45, -45, -45, -45, -45, -28,
	-22, -45, -28, -22, -45, -45, -28, -22, -1, -45,
	17, -33, 15, -45, -33, -45, -45, 15, -33, -45,
	-1, -33, 4, 4, -39, -1, -2, 14, -45, -33,
	-33, -33, -33, -33, -33, -33, -33, -33, -33, -33,
	-33, -33, -33, -33, -33, -33, -33, -33, -33, -9,
	-33, 13, -33, -8, 16, -21, -33, -22, -33, 29,
	17, -33, 15, -33, -45, -33, 29, -33, 29, -3,
	4, -39, -1, -39, -1, -1, -45, -10, 16, -22,
	-45, -45, -45, 5, 47, -45, 29, -45, 29, 16,
	29, -45, -45, -45, 15, -39, -1, -1, -1, -33,
	-45, 5, -1, -33, 17, 16, -45, -45, 17, -45,
	-33, 29, 17, -45, -45, -33, 29, 17, 17, -33,
	-1, 16, -45, 16, -33, -21, -33, -33, 29, 17,
	29, 17, -45, -33, -33, 29, 17, 29, 17, -45,
	-1, -22, 29, 17, -45, -45, -33, 17, 29, 17,
	-45, -45, -33, 17, -45, -33, 17, -33, 17, 17,
	-45, -33, 17, -33, 17, 17, -33, 17, 17, 17,
	-33, 17, 17, 17, 17, 17,
}

var yyDef = [...]int16{
	0, -2, 0, 12, 11, 8, 9, 14, 15, 41,
	17, 19, 20, 21, 22, 23, 24, 25, 26, 27,
	5, 73, 0, 55, 54, 158, 56, -2, 0, 76,
	-2, -2, 30, 31, -2, 33, 34, 35, -2, 37,
	38, 39, 0, 160, 161, 162, 163, 164, 165, 166,
	0, 44, 44, 154, 44, 0, 0, 0, 93, 94,
	0, 0, 157, 159, 44, 10, 42, 13, 16, 1,
	2, 6, 7, 0, 77, 0, 38, 0, 0, -2,
	72, 158, 0, 57, 44, 44, 44, 44, 44, 44,
	44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
	44, 44, 44, 44, 44, 0, 44, 0, 44, 44,
	0, 0, 146, 44, 151, 0, 43, 0, 44, 0,
	90, 91, 92, 44, 44, 0, 18, 3, 4, 74,
	79, 44, 0, 62, 0, 0, 0, 44, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 116,
	117, 0, 114, 115, 0, 0, 112, 113, 75, 0,
	148, 149, 152, 0, 44, 0, 0, 81, 0, 0,
	78, 0, 0, 0, 0, 70, -2, 44, 0, 48,
	49, 50, 51, 52, 53, 95, 96, 97, 98, 99,
	100, 101, 102, 103, 104, 105, 106, 107, 46, 47,
	45, 44, 44, 44, 84, 87, 88, 39, 44, 44,
	147, 150, 153, 0, 0, 0, 44, 44, 44, 0,
	0, 0, 68, 0, 66, 69, 0, 44, 0, 60,
	0, 0, 0, 44, 44, 0, 44, 0, 44, 108,
	44, 0, 0, 0, 80, 0, 64, 67, 65, -2,
	0, 44, 59, 44, 111, 82, 0, 0, 109, 0,
	0, 44, 133, 0, 0, 0, 44, 145, 110, 155,
	63, 0, 0, 83, 85, 86, 89, 0, 44, 132,
	44, 131, 0, 156, 0, 44, 144, 44, 143, 0,
	58, 61, 44, 130, 0, 0, 0, 129, 44, 142,
	0, 0, 0, 141, 0, 0, 125, 0, 127, 128,
	0, 0, 137, 0, 139, 140, 0, 123, 124, 126,
	0, 135, 136, 138, 122, 134,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:145
		{
			yylex.(*parser).parseResult = yyDollar[2].aststmts
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:149
		{
			yylex.(*parser).parseResult = ast.Stmts{}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:153
		{
			yylex.(*parser).parseResult = yyDollar[3].aststmts
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:158
		{
			yylex.(*parser).unexpected("", "")
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:165
		{
			s := yyDollar[1].aststmts
			s = append(s, yyDollar[2].node)
			yyVAL.aststmts = s
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:172
		{
			yyVAL.aststmts = ast.Stmts{yyDollar[1].node}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:178
		{
			yyVAL.aststmts = ast.Stmts{yyDollar[1].node}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:182
		{
			yyVAL.aststmts = ast.Stmts{}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:186
		{
			s := yyDollar[1].aststmts
			s = append(s, yyDollar[2].node)
			yyVAL.aststmts = s
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:232
		{
			yyVAL.nodes = []*ast.Node{yyDollar[1].node}
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:236
		{
			yyVAL.nodes = append(yyVAL.nodes, yyDollar[4].node)
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:241
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(yyDollar[1].nodes, yyDollar[4].nodes, yyDollar[2].item)
		}
	case 48:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:245
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(
				[]*ast.Node{yyDollar[1].node}, []*ast.Node{yyDollar[4].node}, yyDollar[2].item)
		}
	case 49:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:250
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(
				[]*ast.Node{yyDollar[1].node}, []*ast.Node{yyDollar[4].node}, yyDollar[2].item)
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:255
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(
				[]*ast.Node{yyDollar[1].node}, []*ast.Node{yyDollar[4].node}, yyDollar[2].item)
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:260
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(
				[]*ast.Node{yyDollar[1].node}, []*ast.Node{yyDollar[4].node}, yyDollar[2].item)
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:265
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(
				[]*ast.Node{yyDollar[1].node}, []*ast.Node{yyDollar[4].node}, yyDollar[2].item)
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:273
		{
			yyVAL.node = yylex.(*parser).newInExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:278
		{
			yyVAL.node = yylex.(*parser).newBreakStmt(yyDollar[1].item.Pos)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:284
		{
			yyVAL.node = yylex.(*parser).newContinueStmt(yyDollar[1].item.Pos)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:290
		{
			yyVAL.node = yylex.(*parser).newReturnStmt(yyDollar[1].item, nil)
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:294
		{
			yyVAL.node = yylex.(*parser).newReturnStmt(yyDollar[1].item, yyDollar[2].node)
		}
	case 58:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:300
		{
			yyVAL.node = yylex.(*parser).newFuncDeclStmt(yyDollar[1].item, yyDollar[2].node, yyDollar[5].nodes, yyDollar[3].item, yyDollar[7].item, yyDollar[8].astblock)
		}
	case 59:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:304
		{
			yyVAL.node = yylex.(*parser).newFuncDeclStmt(yyDollar[1].item, yyDollar[2].node, nil, yyDollar[3].item, yyDollar[5].item, yyDollar[6].astblock)
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:310
		{
			yyVAL.nodes = []*ast.Node{yyDollar[1].node}
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:314
		{
			yyVAL.nodes = append(yyVAL.nodes, yyDollar[4].node)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:325
		{
			yyVAL.node = yylex.(*parser).newForInStmt(yyDollar[2].node, yyDollar[3].astblock, yyDollar[1].item)
		}
	case 63:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:337
		{
			yyVAL.node = yylex.(*parser).newForStmt(yyDollar[2].node, yyDollar[4].node, yyDollar[6].node, yyDollar[7].astblock)
		}
	case 64:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:341
		{
			yyVAL.node = yylex.(*parser).newForStmt(yyDollar[2].node, yyDollar[4].node, nil, yyDollar[6].astblock)
		}
	case 65:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:345
		{
			yyVAL.node = yylex.(*parser).newForStmt(nil, yyDollar[3].node, yyDollar[5].node, yyDollar[6].astblock)
		}
	case 66:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:349
		{
			yyVAL.node = yylex.(*parser).newForStmt(nil, yyDollar[3].node, nil, yyDollar[5].astblock)
		}
	case 67:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:353
		{
			yyVAL.node = yylex.(*parser).newForStmt(yyDollar[2].node, nil, yyDollar[5].node, yyDollar[6].astblock)
		}
	case 68:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:357
		{
			yyVAL.node = yylex.(*parser).newForStmt(yyDollar[2].node, nil, nil, yyDollar[5].astblock)
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:361
		{
			yyVAL.node = yylex.(*parser).newForStmt(nil, nil, yyDollar[4].node, yyDollar[5].astblock)
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:365
		{
			yyVAL.node = yylex.(*parser).newForStmt(nil, nil, nil, yyDollar[4].astblock)
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:374
		{
			yyVAL.node = yylex.(*parser).newIfElifStmt(yyDollar[1].iflist)
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:378
		{
			yyVAL.node = yylex.(*parser).newIfElifelseStmt(yyDollar[1].iflist, yyDollar[2].item, yyDollar[3].astblock)
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:384
		{
			yyVAL.ifitem = yylex.(*parser).newIfElem(yyDollar[1].item, yyDollar[2].node, yyDollar[3].astblock)
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:390
		{
			yyVAL.iflist = []*ast.IfStmtElem{yyDollar[1].ifitem}
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:394
		{
			yyVAL.iflist = append(yyDollar[1].iflist, yyDollar[2].ifitem)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:400
		{
			yyVAL.ifitem = yylex.(*parser).newIfElem(yyDollar[1].item, yyDollar[2].node, yyDollar[3].astblock)
		}
	case 80:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:408
		{
			yyVAL.astblock = yylex.(*parser).newBlockStmt(yyDollar[1].item, yyDollar[3].aststmts, yyDollar[4].item)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:414
		{
			yyVAL.astblock = yylex.(*parser).newBlockStmt(yyDollar[1].item, ast.Stmts{}, yyDollar[3].item)
		}
	case 82:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:420
		{
			yyVAL.node = yylex.(*parser).newCallExpr(yyDollar[1].node, yyDollar[4].nodes, yyDollar[2].item, yyDollar[6].item)
		}
	case 83:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:424
		{
			yyVAL.node = yylex.(*parser).newCallExpr(yyDollar[1].node, yyDollar[4].nodes, yyDollar[2].item, yyDollar[7].item)
		}
	case 84:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:428
		{
			yyVAL.node = yylex.(*parser).newCallExpr(yyDollar[1].node, nil, yyDollar[2].item, yyDollar[4].item)
		}
	case 85:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:435
		{
			yyVAL.nodes = append(yyVAL.nodes, yyDollar[4].node)
		}
	case 86:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:439
		{
			yyVAL.nodes = append(yyVAL.nodes, yyDollar[4].node)
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:443
		{
			yyVAL.nodes = []*ast.Node{yyDollar[1].node}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:447
		{
			yyVAL.nodes = []*ast.Node{yyDollar[1].node}
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:453
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(
				[]*ast.Node{yyDollar[1].node}, []*ast.Node{yyDollar[4].node}, yyDollar[2].item)
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:460
		{
			yyVAL.node = yylex.(*parser).newUnaryExpr(yyDollar[1].item, yyDollar[2].node)
		}
	case 91:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:464
		{
			yyVAL.node = yylex.(*parser).newUnaryExpr(yyDollar[1].item, yyDollar[2].node)
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:468
		{
			yyVAL.node = yylex.(*parser).newUnaryExpr(yyDollar[1].item, yyDollar[2].node)
		}
	case 95:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:476
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 96:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:480
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 97:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:484
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 98:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:488
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 99:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:492
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 100:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:496
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 101:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:500
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 102:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:504
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 103:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:511
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 104:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:515
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:519
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 106:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:523
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:527
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 108:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:534
		{
			yyVAL.node = yylex.(*parser).newParenExpr(yyDollar[1].item, yyDollar[3].node, yyDollar[5].item)
		}
	case 109:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:541
		{
			yyVAL.node = yylex.(*parser).newIndexExpr(yyDollar[1].node, yyDollar[2].item, yyDollar[4].node, yyDollar[6].item)
		}
	case 110:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:546
		{
			yyVAL.node = yylex.(*parser).newIndexExpr(nil, yyDollar[2].item, yyDollar[4].node, yyDollar[6].item)
		}
	case 111:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:550
		{
			yyVAL.node = yylex.(*parser).newIndexExpr(yyDollar[1].node, yyDollar[2].item, yyDollar[4].node, yyDollar[6].item)
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:559
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:563
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:567
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:571
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:575
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:579
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:586
		{
			yyVAL.node = yyDollar[1].node
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:590
		{
			yyVAL.node = yyDollar[1].node
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:594
		{
			yyVAL.node = yyDollar[1].node
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:598
		{
			yyVAL.node = yyDollar[1].node
		}
	case 122:
		yyDollar = yyS[yypt-11 : yypt+1]
//line gram.y:604
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node, yyDollar[10].node, true, yyDollar[2].item, yyDollar[11].item)
		}
	case 123:
		yyDollar = yyS[yypt-10 : yypt+1]
//line gram.y:608
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node, nil, true, yyDollar[2].item, yyDollar[10].item)
		}
	case 124:
		yyDollar = yyS[yypt-10 : yypt+1]
//line gram.y:612
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, nil, yyDollar[9].node, true, yyDollar[2].item, yyDollar[10].item)
		}
	case 125:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:616
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, nil, nil, true, yyDollar[2].item, yyDollar[9].item)
		}
	case 126:
		yyDollar = yyS[yypt-10 : yypt+1]
//line gram.y:620
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, yyDollar[6].node, yyDollar[9].node, true, yyDollar[2].item, yyDollar[10].item)
		}
	case 127:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:624
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, yyDollar[6].node, nil, true, yyDollar[2].item, yyDollar[9].item)
		}
	case 128:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:628
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, nil, yyDollar[8].node, true, yyDollar[2].item, yyDollar[9].item)
		}
	case 129:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:632
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, nil, nil, true, yyDollar[2].item, yyDollar[8].item)
		}
	case 130:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:636
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node, nil, false, yyDollar[2].item, yyDollar[8].item)
		}
	case 131:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:640
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, yyDollar[6].node, nil, false, yyDollar[2].item, yyDollar[7].item)
		}
	case 132:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:644
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, nil, nil, false, yyDollar[2].item, yyDollar[7].item)
		}
	case 133:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:648
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, nil, nil, false, yyDollar[2].item, yyDollar[6].item)
		}
	case 134:
		yyDollar = yyS[yypt-11 : yypt+1]
//line gram.y:652
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node, yyDollar[10].node, true, yyDollar[2].item, yyDollar[11].item)
		}
	case 135:
		yyDollar = yyS[yypt-10 : yypt+1]
//line gram.y:656
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node, nil, true, yyDollar[2].item, yyDollar[10].item)
		}
	case 136:
		yyDollar = yyS[yypt-10 : yypt+1]
//line gram.y:660
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, nil, yyDollar[9].node, true, yyDollar[2].item, yyDollar[10].item)
		}
	case 137:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:664
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, nil, nil, true, yyDollar[2].item, yyDollar[9].item)
		}
	case 138:
		yyDollar = yyS[yypt-10 : yypt+1]
//line gram.y:668
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, yyDollar[6].node, yyDollar[9].node, true, yyDollar[2].item, yyDollar[10].item)
		}
	case 139:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:672
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, yyDollar[6].node, nil, true, yyDollar[2].item, yyDollar[9].item)
		}
	case 140:
		yyDollar = yyS[yypt-9 : yypt+1]
//line gram.y:676
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, nil, yyDollar[8].node, true, yyDollar[2].item, yyDollar[9].item)
		}
	case 141:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:680
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, nil, nil, true, yyDollar[2].item, yyDollar[8].item)
		}
	case 142:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:684
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node, nil, false, yyDollar[2].item, yyDollar[8].item)
		}
	case 143:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:688
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, yyDollar[6].node, nil, false, yyDollar[2].item, yyDollar[7].item)
		}
	case 144:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:692
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, nil, nil, false, yyDollar[2].item, yyDollar[7].item)
		}
	case 145:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:696
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, nil, nil, nil, false, yyDollar[2].item, yyDollar[6].item)
		}
	case 146:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:702
		{
			yyVAL.node = yylex.(*parser).newListLiteralEnd(yyVAL.node, yyDollar[2].item.Pos)
		}
	case 147:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:706
		{
			yyVAL.node = yylex.(*parser).newListLiteralEnd(yyVAL.node, yyDollar[4].item.Pos)
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:710
		{
			yyVAL.node = yylex.(*parser).newListLiteralStart(yyDollar[1].item.Pos)
			yyVAL.node = yylex.(*parser).newListLiteralEnd(yyVAL.node, yyDollar[3].item.Pos)
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:717
		{
			yyVAL.node = yylex.(*parser).newListLiteralStart(yyDollar[1].item.Pos)
			yyVAL.node = yylex.(*parser).newListLiteralAppendExpr(yyVAL.node, yyDollar[3].node)
		}
	case 150:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:722
		{
			yyVAL.node = yylex.(*parser).newListLiteralAppendExpr(yyVAL.node, yyDollar[4].node)
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:730
		{
			yyVAL.node = yylex.(*parser).newMapLiteralEnd(yyVAL.node, yyDollar[3].item.Pos)
		}
	case 153:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:734
		{
			yyVAL.node = yylex.(*parser).newMapLiteralEnd(yyVAL.node, yyDollar[4].item.Pos)
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:738
		{
			yyVAL.node = yylex.(*parser).newMapLiteralStart(yyDollar[1].astblock.LBracePos.Pos)
			yyVAL.node = yylex.(*parser).newMapLiteralEnd(yyVAL.node, yyDollar[1].astblock.RBracePos.Pos)
		}
	case 155:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:745
		{
			yyVAL.node = yylex.(*parser).newMapLiteralStart(yyDollar[1].item.Pos)
			yyVAL.node = yylex.(*parser).newMapLiteralAppendExpr(yyVAL.node, yyDollar[3].node, yyDollar[6].node)
		}
	case 156:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:750
		{
			yyVAL.node = yylex.(*parser).newMapLiteralAppendExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node)
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:757
		{
			yyVAL.node = yylex.(*parser).newIdentifierLiteral(yyDollar[1].item)
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:761
		{
			yyVAL.node = yylex.(*parser).newIdentifierLiteral(yyDollar[1].item)
		}
	case 159:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:765
		{
			yyDollar[1].item.Val = yylex.(*parser).unquoteString(yyDollar[1].item.Val)
			yyVAL.node = yylex.(*parser).newIdentifierLiteral(yyDollar[1].item)
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:772
		{
			yyVAL.node = yylex.(*parser).newNumberLiteral(yyDollar[1].item)
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:776
		{
			yyVAL.node = yylex.(*parser).newBoolLiteral(yyDollar[1].item.Pos, true)
		}
	case 162:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:780
		{
			yyVAL.node = yylex.(*parser).newBoolLiteral(yyDollar[1].item.Pos, false)
		}
	case 163:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:784
		{
			yyDollar[1].item.Val = yylex.(*parser).unquoteString(yyDollar[1].item.Val)
			yyVAL.node = yylex.(*parser).newStringLiteral(yyDollar[1].item)
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:789
		{
			yyDollar[1].item.Val = yylex.(*parser).unquoteMultilineString(yyDollar[1].item.Val)
			yyVAL.node = yylex.(*parser).newStringLiteral(yyDollar[1].item)
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:794
		{
			yyVAL.node = yylex.(*parser).newNilLiteral(yyDollar[1].item.Pos)
		}
	case 166:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:798
		{
			yyVAL.node = yylex.(*parser).newNilLiteral(yyDollar[1].item.Pos)
		}
	}
	goto yystack /* stack new state and value */
}
