// Code generated by goyacc -o gram_y.go gram.y. DO NOT EDIT.

//line gram.y:7
package parser

import __yyfmt__ "fmt"

//line gram.y:7

import (
	ast "github.com/GuanceCloud/platypus/pkg/ast"
)

//line gram.y:15
type yySymType struct {
	yys      int
	aststmts ast.Stmts
	astblock *ast.BlockStmt

	ifitem *ast.IfStmtElem
	iflist []*ast.IfStmtElem
	node   *ast.Node
	nodes  []*ast.Node
	item   Item
}

const SEMICOLON = 57346
const COMMA = 57347
const COMMENT = 57348
const DOT = 57349
const EOF = 57350
const ERROR = 57351
const ID = 57352
const NUMBER = 57353
const LEFT_PAREN = 57354
const LEFT_BRACKET = 57355
const LEFT_BRACE = 57356
const RIGHT_BRACE = 57357
const RIGHT_PAREN = 57358
const RIGHT_BRACKET = 57359
const SPACE = 57360
const STRING = 57361
const QUOTED_STRING = 57362
const MULTILINE_STRING = 57363
const FOR = 57364
const IN = 57365
const WHILE = 57366
const BREAK = 57367
const CONTINUE = 57368
const RETURN = 57369
const EOL = 57370
const COLON = 57371
const STR = 57372
const INT = 57373
const FLOAT = 57374
const BOOL = 57375
const LIST = 57376
const MAP = 57377
const operatorsStart = 57378
const ADD = 57379
const DIV = 57380
const GTE = 57381
const GT = 57382
const NOT = 57383
const LT = 57384
const LTE = 57385
const MOD = 57386
const MUL = 57387
const NEQ = 57388
const EQ = 57389
const EQEQ = 57390
const SUB = 57391
const ADD_EQ = 57392
const SUB_EQ = 57393
const DIV_EQ = 57394
const MUL_EQ = 57395
const MOD_EQ = 57396
const operatorsEnd = 57397
const keywordsStart = 57398
const TRUE = 57399
const FALSE = 57400
const IDENTIFIER = 57401
const AND = 57402
const OR = 57403
const NIL = 57404
const NULL = 57405
const IF = 57406
const ELIF = 57407
const ELSE = 57408
const keywordsEnd = 57409
const startSymbolsStart = 57410
const START_STMTS = 57411
const startSymbolsEnd = 57412
const UMINUS = 57413

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SEMICOLON",
	"COMMA",
	"COMMENT",
	"DOT",
	"EOF",
	"ERROR",
	"ID",
	"NUMBER",
	"LEFT_PAREN",
	"LEFT_BRACKET",
	"LEFT_BRACE",
	"RIGHT_BRACE",
	"RIGHT_PAREN",
	"RIGHT_BRACKET",
	"SPACE",
	"STRING",
	"QUOTED_STRING",
	"MULTILINE_STRING",
	"FOR",
	"IN",
	"WHILE",
	"BREAK",
	"CONTINUE",
	"RETURN",
	"EOL",
	"COLON",
	"STR",
	"INT",
	"FLOAT",
	"BOOL",
	"LIST",
	"MAP",
	"operatorsStart",
	"ADD",
	"DIV",
	"GTE",
	"GT",
	"NOT",
	"LT",
	"LTE",
	"MOD",
	"MUL",
	"NEQ",
	"EQ",
	"EQEQ",
	"SUB",
	"ADD_EQ",
	"SUB_EQ",
	"DIV_EQ",
	"MUL_EQ",
	"MOD_EQ",
	"operatorsEnd",
	"keywordsStart",
	"TRUE",
	"FALSE",
	"IDENTIFIER",
	"AND",
	"OR",
	"NIL",
	"NULL",
	"IF",
	"ELIF",
	"ELSE",
	"keywordsEnd",
	"startSymbolsStart",
	"START_STMTS",
	"startSymbolsEnd",
	"UMINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line gram.y:660

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 179,
	1, 69,
	4, 69,
	8, 69,
	15, 69,
	28, 69,
	-2, 123,
}

const yyPrivate = 57344

const yyLast = 1605

var yyAct = [...]int16{
	73, 34, 209, 23, 3, 69, 67, 23, 23, 238,
	62, 9, 60, 55, 266, 262, 56, 38, 49, 46,
	58, 17, 271, 110, 118, 41, 57, 42, 35, 90,
	93, 258, 9, 259, 102, 71, 94, 92, 103, 100,
	101, 91, 74, 50, 244, 247, 9, 52, 119, 70,
	93, 112, 113, 114, 166, 51, 94, 92, 122, 205,
	99, 81, 36, 39, 40, 63, 98, 105, 43, 44,
	123, 2, 117, 126, 239, 90, 93, 82, 83, 104,
	86, 87, 94, 92, 88, 66, 89, 91, 98, 64,
	106, 115, 55, 96, 4, 56, 148, 150, 85, 152,
	95, 155, 159, 8, 160, 57, 97, 10, 165, 65,
	102, 61, 168, 125, 1, 100, 101, 171, 48, 108,
	222, 16, 6, 5, 25, 45, 174, 59, 120, 181,
	182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
	192, 193, 194, 195, 196, 197, 198, 199, 200, 74,
	202, 26, 204, 47, 27, 206, 33, 32, 210, 212,
	153, 28, 156, 177, 216, 161, 54, 53, 218, 31,
	220, 30, 29, 23, 11, 15, 90, 93, 82, 83,
	14, 86, 87, 94, 92, 88, 121, 89, 91, 121,
	13, 240, 12, 207, 19, 68, 24, 74, 74, 124,
	7, 0, 230, 0, 232, 0, 235, 0, 0, 0,
	0, 224, 226, 0, 0, 242, 0, 0, 0, 0,
	211, 0, 121, 0, 0, 0, 0, 0, 0, 0,
	252, 0, 162, 0, 0, 257, 0, 0, 107, 109,
	0, 111, 121, 0, 0, 74, 179, 267, 0, 0,
	116, 0, 173, 0, 0, 269, 178, 270, 0, 248,
	0, 272, 274, 273, 275, 0, 276, 128, 129, 130,
	131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
	141, 142, 143, 144, 145, 146, 147, 149, 151, 0,
	154, 0, 157, 158, 179, 179, 121, 163, 0, 0,
	0, 0, 167, 0, 225, 227, 228, 169, 0, 0,
	81, 0, 0, 0, 172, 0, 221, 0, 0, 0,
	0, 0, 0, 211, 90, 93, 82, 83, 0, 86,
	87, 94, 92, 88, 75, 89, 91, 76, 77, 79,
	78, 80, 179, 121, 0, 121, 0, 85, 84, 0,
	0, 0, 249, 250, 0, 251, 0, 0, 0, 0,
	219, 0, 0, 0, 81, 0, 0, 121, 0, 0,
	0, 0, 229, 0, 0, 0, 0, 268, 90, 93,
	82, 83, 0, 86, 87, 94, 92, 88, 75, 89,
	91, 76, 77, 79, 78, 80, 0, 234, 236, 237,
	0, 85, 84, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 245, 246, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 254, 0, 256, 0, 0, 0, 0,
	260, 261, 0, 263, 18, 265, 0, 55, 0, 0,
	56, 38, 49, 46, 58, 170, 0, 0, 0, 41,
	57, 42, 20, 0, 0, 22, 21, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 50, 0, 0,
	0, 52, 0, 0, 0, 0, 0, 0, 0, 51,
	0, 0, 0, 0, 0, 0, 0, 39, 40, 0,
	0, 0, 43, 44, 37, 18, 0, 0, 55, 0,
	0, 56, 38, 49, 46, 58, 0, 0, 0, 0,
	41, 57, 42, 20, 0, 0, 22, 21, 0, 60,
	0, 0, 0, 0, 0, 0, 0, 0, 50, 0,
	0, 0, 52, 0, 0, 0, 0, 0, 0, 0,
	51, 0, 0, 0, 0, 0, 0, 0, 39, 40,
	0, 0, 0, 43, 44, 37, 18, 0, 0, 55,
	0, 0, 56, 38, 49, 46, 58, 0, 0, 0,
	0, 41, 57, 42, 20, 0, 0, 22, 21, 0,
	9, 0, 0, 0, 0, 0, 0, 0, 0, 50,
	0, 0, 0, 52, 0, 0, 0, 0, 0, 0,
	0, 51, 0, 0, 0, 0, 0, 0, 0, 39,
	40, 0, 0, 0, 43, 44, 37, 55, 0, 0,
	56, 38, 49, 46, 58, 0, 0, 0, 0, 41,
	57, 42, 20, 0, 0, 22, 21, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 50, 0, 55,
	0, 52, 56, 38, 49, 46, 58, 0, 0, 51,
	0, 41, 57, 42, 0, 0, 0, 39, 40, 0,
	9, 0, 43, 44, 37, 0, 0, 0, 0, 50,
	0, 55, 0, 52, 56, 38, 49, 46, 58, 217,
	0, 51, 0, 41, 57, 42, 0, 0, 0, 39,
	40, 0, 0, 0, 43, 44, 0, 0, 0, 0,
	0, 50, 0, 0, 55, 52, 0, 56, 38, 49,
	46, 58, 0, 51, 215, 0, 41, 57, 42, 0,
	0, 39, 40, 0, 0, 0, 43, 44, 0, 0,
	0, 0, 0, 0, 50, 0, 55, 0, 52, 56,
	38, 49, 46, 58, 0, 208, 51, 0, 41, 57,
	42, 0, 0, 0, 39, 40, 0, 0, 0, 43,
	44, 0, 0, 0, 0, 175, 50, 0, 55, 0,
	52, 56, 38, 49, 46, 58, 0, 0, 51, 0,
	41, 57, 42, 0, 0, 0, 39, 40, 0, 0,
	0, 43, 44, 0, 0, 0, 0, 0, 50, 0,
	55, 0, 52, 56, 38, 49, 46, 58, 170, 0,
	51, 0, 41, 57, 42, 0, 0, 0, 39, 40,
	0, 0, 0, 43, 44, 0, 0, 0, 0, 0,
	50, 0, 0, 55, 52, 0, 56, 38, 49, 46,
	58, 0, 51, 164, 0, 41, 57, 42, 0, 0,
	39, 40, 0, 0, 0, 43, 44, 0, 0, 0,
	0, 0, 127, 50, 0, 55, 0, 52, 56, 38,
	49, 46, 58, 0, 0, 51, 0, 41, 57, 42,
	0, 0, 0, 39, 40, 0, 0, 0, 43, 44,
	0, 0, 0, 0, 72, 50, 0, 55, 0, 52,
	56, 38, 49, 46, 58, 0, 0, 51, 0, 41,
	57, 42, 0, 0, 0, 39, 40, 0, 0, 0,
	43, 44, 0, 0, 0, 0, 0, 50, 0, 55,
	0, 52, 56, 38, 49, 46, 58, 0, 0, 51,
	0, 41, 57, 42, 0, 0, 0, 39, 40, 0,
	0, 0, 43, 44, 0, 0, 0, 0, 0, 50,
	0, 55, 0, 52, 56, 38, 49, 46, 180, 0,
	0, 51, 0, 41, 57, 42, 0, 0, 0, 39,
	40, 0, 0, 0, 43, 44, 0, 0, 0, 0,
	0, 50, 0, 0, 0, 52, 0, 0, 0, 0,
	0, 0, 0, 51, 81, 0, 0, 0, 0, 9,
	241, 39, 40, 0, 0, 0, 43, 44, 90, 93,
	82, 83, 0, 86, 87, 94, 92, 88, 213, 89,
	91, 0, 0, 0, 81, 0, 0, 0, 0, 0,
	214, 85, 84, 0, 0, 0, 0, 0, 90, 93,
	82, 83, 0, 86, 87, 94, 92, 88, 279, 89,
	91, 0, 0, 0, 81, 0, 0, 0, 0, 0,
	0, 85, 84, 0, 0, 0, 0, 0, 90, 93,
	82, 83, 0, 86, 87, 94, 92, 88, 278, 89,
	91, 0, 0, 0, 81, 0, 0, 0, 0, 0,
	0, 85, 84, 0, 0, 0, 0, 0, 90, 93,
	82, 83, 0, 86, 87, 94, 92, 88, 277, 89,
	91, 0, 0, 0, 81, 0, 0, 0, 0, 0,
	0, 85, 84, 0, 0, 0, 0, 0, 90, 93,
	82, 83, 0, 86, 87, 94, 92, 88, 0, 89,
	91, 81, 0, 0, 0, 0, 9, 0, 0, 0,
	0, 85, 84, 0, 0, 90, 93, 82, 83, 0,
	86, 87, 94, 92, 88, 264, 89, 91, 0, 0,
	0, 81, 0, 0, 0, 0, 0, 0, 85, 84,
	0, 0, 0, 0, 0, 90, 93, 82, 83, 0,
	86, 87, 94, 92, 88, 213, 89, 91, 0, 0,
	0, 81, 0, 0, 0, 0, 0, 0, 85, 84,
	0, 0, 0, 0, 0, 90, 93, 82, 83, 0,
	86, 87, 94, 92, 88, 255, 89, 91, 0, 0,
	0, 81, 0, 0, 0, 0, 0, 0, 85, 84,
	0, 0, 0, 0, 0, 90, 93, 82, 83, 0,
	86, 87, 94, 92, 88, 253, 89, 91, 0, 0,
	0, 81, 0, 0, 0, 0, 0, 0, 85, 84,
	0, 0, 0, 0, 0, 90, 93, 82, 83, 0,
	86, 87, 94, 92, 88, 0, 89, 91, 81, 0,
	0, 0, 0, 0, 243, 0, 0, 0, 85, 84,
	0, 0, 90, 93, 82, 83, 0, 86, 87, 94,
	92, 88, 0, 89, 91, 81, 0, 0, 0, 0,
	0, 233, 0, 0, 0, 85, 84, 0, 0, 90,
	93, 82, 83, 0, 86, 87, 94, 92, 88, 0,
	89, 91, 81, 0, 0, 0, 0, 0, 231, 0,
	223, 0, 85, 84, 0, 0, 90, 93, 82, 83,
	0, 86, 87, 94, 92, 88, 0, 89, 91, 81,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 85,
	84, 0, 0, 90, 93, 82, 83, 0, 86, 87,
	94, 92, 88, 0, 89, 91, 81, 0, 0, 0,
	0, 0, 221, 0, 0, 0, 85, 84, 0, 0,
	90, 93, 82, 83, 0, 86, 87, 94, 92, 88,
	0, 89, 91, 81, 0, 0, 0, 0, 0, 203,
	0, 0, 0, 85, 84, 0, 0, 90, 93, 82,
	83, 0, 86, 87, 94, 92, 88, 0, 89, 91,
	81, 0, 0, 0, 0, 0, 201, 0, 176, 0,
	85, 84, 0, 0, 90, 93, 82, 83, 0, 86,
	87, 94, 92, 88, 0, 89, 91, 81, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 85, 84, 0,
	0, 90, 93, 82, 83, 122, 86, 87, 94, 92,
	88, 0, 89, 91, 81, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 85, 84, 0, 0, 90, 93,
	82, 83, 0, 86, 87, 94, 92, 88, 0, 89,
	91, 81, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 85, 84, 0, 0, 90, 93, 82, 83, 0,
	86, 87, 94, 92, 88, 0, 89, 91, 81, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 85, 84,
	0, 0, 90, 93, 82, 83, 0, 86, 87, 94,
	92, 88, 0, 89, 91,
}

var yyPact = [...]int16{
	2, 86, 552, -1000, -1000, -1000, 491, 610, 61, -1000,
	81, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -60,
	900, -1000, -1000, 341, -1000, 87, 80, -1000, -1000, -1000,
	-1000, -1000, 99, -1000, 53, -1000, 103, 932, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 62, -17, 18, -1000, -17,
	932, 932, 932, -1000, -1000, 78, -1000, -1000, -17, -1000,
	-1000, 61, 20, -1000, -1000, -1000, -1000, 44, -1000, 932,
	44, 109, 868, 341, -1000, -17, -17, -17, -17, -17,
	-17, -17, -17, -17, -17, -17, -17, -17, -17, -17,
	-17, -17, -17, -17, -17, 642, 642, 85, -17, 85,
	-17, 642, 85, 1501, -1000, -17, -1000, 836, -16, 39,
	-17, 932, -1000, -1000, -1000, -17, 803, 20, -1000, -1000,
	-1000, -1000, -17, 1501, -1000, 771, 1474, 964, 932, 932,
	932, 932, 932, 932, 932, 932, 932, 932, 932, 932,
	932, 932, 932, 932, 932, 932, 932, 932, 1447, 932,
	1420, 932, 75, 46, 932, 75, 46, 739, 932, 1021,
	75, 46, -1000, 707, -1000, 1528, -1000, 674, 1138, 932,
	-1000, 1393, 430, -1000, 1366, 964, 964, 44, -1000, -1000,
	-17, 1528, 1528, 1528, 1528, 1528, 1528, 139, -8, -8,
	38, 1555, -8, -8, -8, -8, 12, 12, -1000, -1000,
	-1000, 932, 1339, 932, 1312, 642, 1138, 4, -1000, -1000,
	1528, 27, 991, -1000, 932, -1000, 1528, -1000, 1285, 28,
	1138, -17, 30, 964, 44, -1000, 44, -1000, -1000, 430,
	1258, -17, 1228, -17, 932, 1198, 14, 17, -17, -17,
	-2, -17, 1168, -17, -1000, -3, 932, -1000, 44, -1000,
	-1000, -1000, 287, -1000, 932, -1000, 932, 1138, -1000, -1000,
	6, 932, -1000, 932, -1000, 932, -1000, 1528, -1000, 1111,
	1081, -1000, 1528, -1000, 1528, 1051, 1528, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 128, 118, 120, 200, 196, 195, 194, 193, 103,
	21, 192, 190, 180, 175, 174, 172, 2, 62, 171,
	169, 167, 166, 161, 1, 157, 156, 28, 0, 154,
	153, 151, 125, 124, 35, 121, 114, 10, 107, 119,
	191,
}

var yyR1 = [...]int8{
	0, 37, 37, 37, 37, 38, 38, 38, 36, 36,
	36, 36, 36, 3, 3, 3, 4, 4, 4, 9,
	9, 9, 9, 9, 9, 9, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 35, 39,
	39, 40, 40, 10, 10, 10, 10, 10, 10, 27,
	14, 13, 11, 12, 12, 12, 12, 12, 12, 12,
	12, 34, 34, 15, 15, 5, 7, 7, 6, 1,
	1, 2, 16, 16, 16, 8, 8, 8, 8, 17,
	19, 19, 19, 20, 20, 21, 21, 21, 21, 21,
	21, 21, 21, 22, 22, 22, 22, 22, 23, 24,
	24, 24, 24, 25, 25, 25, 25, 25, 25, 26,
	26, 26, 26, 26, 26, 31, 31, 31, 32, 32,
	32, 29, 29, 29, 30, 30, 18, 18, 33, 33,
	33, 33, 33, 33, 33,
}

var yyR2 = [...]int8{
	0, 1, 1, 2, 2, 1, 2, 2, 2, 2,
	3, 2, 1, 2, 1, 1, 2, 1, 3, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	2, 1, 0, 4, 4, 4, 4, 4, 4, 4,
	1, 1, 3, 7, 6, 6, 5, 6, 5, 5,
	4, 1, 1, 1, 3, 3, 1, 2, 3, 1,
	4, 3, 6, 7, 4, 4, 4, 1, 1, 4,
	2, 2, 2, 1, 1, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 5, 6,
	6, 6, 4, 3, 3, 3, 3, 3, 3, 6,
	8, 6, 8, 6, 8, 2, 4, 3, 3, 4,
	2, 3, 4, 1, 6, 7, 1, 1, 1, 1,
	1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -36, 69, 2, 8, -3, -39, -4, -9, 28,
	-38, -15, -11, -12, -13, -14, -35, -10, 4, -7,
	22, 26, 25, -28, -5, -33, -31, -29, -23, -16,
	-19, -20, -25, -26, -24, -27, -18, 64, 11, 57,
	58, 19, 21, 62, 63, -32, 13, -30, -2, 12,
	37, 49, 41, -21, -22, 7, 10, 20, 14, -3,
	28, -9, -37, 4, 28, 28, 4, 66, -6, 65,
	-27, -34, 4, -28, -10, 47, 50, 51, 53, 52,
	54, 23, 39, 40, 61, 60, 42, 43, 46, 48,
	37, 49, 45, 38, 44, 13, 13, 7, 13, 7,
	12, 13, 7, -28, 17, 5, 28, -40, -39, -40,
	5, -40, -28, -28, -28, 13, -40, -37, 4, 28,
	-1, -2, 14, -28, -1, 4, -28, 4, -40, -40,
	-40, -40, -40, -40, -40, -40, -40, -40, -40, -40,
	-40, -40, -40, -40, -40, -40, -40, -40, -28, -40,
	-28, -40, -24, -18, -40, -24, -18, -40, -40, -28,
	-24, -18, -1, -40, 17, -28, 15, -40, -28, -40,
	15, -28, -40, -1, -28, 4, 4, -34, -1, -2,
	14, -28, -28, -28, -28, -28, -28, -28, -28, -28,
	-28, -28, -28, -28, -28, -28, -28, -28, -28, -28,
	-28, 29, -28, 29, -28, 13, -28, -8, 16, -17,
	-28, -18, -28, 17, 29, 17, -28, 15, -28, -40,
	-28, 29, -3, 4, -34, -1, -34, -1, -1, -40,
	-28, 29, -28, 29, -40, -28, -40, -40, 5, 47,
	-40, 29, -28, 29, 16, -40, -40, 15, -34, -1,
	-1, -1, -28, 17, -40, 17, -40, -28, 17, 16,
	-40, -40, 17, -40, 17, -40, 17, -28, -1, -28,
	-28, 16, -28, -17, -28, -28, -28, 17, 17, 17,
}

var yyDef = [...]int16{
	0, -2, 0, 12, 11, 8, 9, 14, 15, 39,
	17, 19, 20, 21, 22, 23, 24, 25, 5, 63,
	0, 51, 50, 38, 66, 26, 27, 28, 29, 30,
	31, 32, 33, 34, 35, 36, 37, 0, 128, 129,
	130, 131, 132, 133, 134, 0, 42, 42, 123, 42,
	0, 0, 0, 83, 84, 0, 126, 127, 42, 10,
	40, 13, 16, 1, 2, 6, 7, 0, 67, 0,
	36, 0, 0, 61, 62, 42, 42, 42, 42, 42,
	42, 42, 42, 42, 42, 42, 42, 42, 42, 42,
	42, 42, 42, 42, 42, 0, 0, 0, 42, 0,
	42, 0, 0, 0, 115, 42, 120, 0, 41, 0,
	42, 0, 80, 81, 82, 42, 0, 18, 3, 4,
	64, 69, 42, 0, 52, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 107, 108, 0, 105, 106, 0, 0, 0,
	103, 104, 65, 0, 117, 118, 121, 0, 42, 0,
	71, 0, 0, 68, 0, 0, 0, 0, 60, -2,
	42, 43, 44, 45, 46, 47, 48, 49, 85, 86,
	87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
	97, 0, 0, 0, 0, 0, 42, 42, 74, 77,
	78, 37, 42, 102, 0, 116, 119, 122, 0, 0,
	42, 42, 0, 0, 0, 58, 0, 56, 59, 0,
	0, 42, 0, 42, 0, 0, 0, 0, 42, 42,
	0, 42, 0, 42, 98, 0, 0, 70, 0, 54,
	57, 55, 38, 111, 0, 113, 0, 42, 101, 72,
	0, 0, 99, 0, 109, 0, 100, 124, 53, 0,
	0, 73, 75, 76, 79, 0, 125, 112, 114, 110,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:140
		{
			yylex.(*parser).parseResult = yyDollar[2].aststmts
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:144
		{
			yylex.(*parser).parseResult = ast.Stmts{}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:148
		{
			yylex.(*parser).parseResult = yyDollar[3].aststmts
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:153
		{
			yylex.(*parser).unexpected("", "")
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:160
		{
			s := yyDollar[1].aststmts
			s = append(s, yyDollar[2].node)
			yyVAL.aststmts = s
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:167
		{
			yyVAL.aststmts = ast.Stmts{yyDollar[1].node}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:173
		{
			yyVAL.aststmts = ast.Stmts{yyDollar[1].node}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:177
		{
			yyVAL.aststmts = ast.Stmts{}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:181
		{
			s := yyDollar[1].aststmts
			s = append(s, yyDollar[2].node)
			yyVAL.aststmts = s
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:224
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:228
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:232
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:236
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:240
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 48:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:244
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 49:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:251
		{
			yyVAL.node = yylex.(*parser).newInExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:256
		{
			yyVAL.node = yylex.(*parser).newBreakStmt(yyDollar[1].item.Pos)
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:262
		{
			yyVAL.node = yylex.(*parser).newContinueStmt(yyDollar[1].item.Pos)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:273
		{
			yyVAL.node = yylex.(*parser).newForInStmt(yyDollar[2].node, yyDollar[3].astblock, yyDollar[1].item)
		}
	case 53:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:285
		{
			yyVAL.node = yylex.(*parser).newForStmt(yyDollar[2].node, yyDollar[4].node, yyDollar[6].node, yyDollar[7].astblock)
		}
	case 54:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:289
		{
			yyVAL.node = yylex.(*parser).newForStmt(yyDollar[2].node, yyDollar[4].node, nil, yyDollar[6].astblock)
		}
	case 55:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:293
		{
			yyVAL.node = yylex.(*parser).newForStmt(nil, yyDollar[3].node, yyDollar[5].node, yyDollar[6].astblock)
		}
	case 56:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:297
		{
			yyVAL.node = yylex.(*parser).newForStmt(nil, yyDollar[3].node, nil, yyDollar[5].astblock)
		}
	case 57:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:301
		{
			yyVAL.node = yylex.(*parser).newForStmt(yyDollar[2].node, nil, yyDollar[5].node, yyDollar[6].astblock)
		}
	case 58:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:305
		{
			yyVAL.node = yylex.(*parser).newForStmt(yyDollar[2].node, nil, nil, yyDollar[5].astblock)
		}
	case 59:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:309
		{
			yyVAL.node = yylex.(*parser).newForStmt(nil, nil, yyDollar[4].node, yyDollar[5].astblock)
		}
	case 60:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:313
		{
			yyVAL.node = yylex.(*parser).newForStmt(nil, nil, nil, yyDollar[4].astblock)
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:322
		{
			yyVAL.node = yylex.(*parser).newIfElifStmt(yyDollar[1].iflist)
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:326
		{
			yyVAL.node = yylex.(*parser).newIfElifelseStmt(yyDollar[1].iflist, yyDollar[2].item, yyDollar[3].astblock)
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:332
		{
			yyVAL.ifitem = yylex.(*parser).newIfElem(yyDollar[1].item, yyDollar[2].node, yyDollar[3].astblock)
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:338
		{
			yyVAL.iflist = []*ast.IfStmtElem{yyDollar[1].ifitem}
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:342
		{
			yyVAL.iflist = append(yyDollar[1].iflist, yyDollar[2].ifitem)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:348
		{
			yyVAL.ifitem = yylex.(*parser).newIfElem(yyDollar[1].item, yyDollar[2].node, yyDollar[3].astblock)
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:356
		{
			yyVAL.astblock = yylex.(*parser).newBlockStmt(yyDollar[1].item, yyDollar[3].aststmts, yyDollar[4].item)
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:362
		{
			yyVAL.astblock = yylex.(*parser).newBlockStmt(yyDollar[1].item, ast.Stmts{}, yyDollar[3].item)
		}
	case 72:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:368
		{
			yyVAL.node = yylex.(*parser).newCallExpr(yyDollar[1].node, yyDollar[4].nodes, yyDollar[2].item, yyDollar[6].item)
		}
	case 73:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:372
		{
			yyVAL.node = yylex.(*parser).newCallExpr(yyDollar[1].node, yyDollar[4].nodes, yyDollar[2].item, yyDollar[7].item)
		}
	case 74:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:376
		{
			yyVAL.node = yylex.(*parser).newCallExpr(yyDollar[1].node, nil, yyDollar[2].item, yyDollar[4].item)
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:383
		{
			yyVAL.nodes = append(yyVAL.nodes, yyDollar[4].node)
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:387
		{
			yyVAL.nodes = append(yyVAL.nodes, yyDollar[4].node)
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:391
		{
			yyVAL.nodes = []*ast.Node{yyDollar[1].node}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:395
		{
			yyVAL.nodes = []*ast.Node{yyDollar[1].node}
		}
	case 79:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:401
		{
			yyVAL.node = yylex.(*parser).newAssignmentStmt(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:407
		{
			yyVAL.node = yylex.(*parser).newUnaryExpr(yyDollar[1].item, yyDollar[2].node)
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:411
		{
			yyVAL.node = yylex.(*parser).newUnaryExpr(yyDollar[1].item, yyDollar[2].node)
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:415
		{
			yyVAL.node = yylex.(*parser).newUnaryExpr(yyDollar[1].item, yyDollar[2].node)
		}
	case 85:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:423
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 86:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:427
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 87:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:431
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 88:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:435
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:439
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 90:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:443
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 91:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:447
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 92:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:451
		{
			yyVAL.node = yylex.(*parser).newConditionalExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 93:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:458
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 94:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:462
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 95:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:466
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 96:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:470
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 97:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:474
		{
			yyVAL.node = yylex.(*parser).newArithmeticExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[2].item)
		}
	case 98:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:481
		{
			yyVAL.node = yylex.(*parser).newParenExpr(yyDollar[1].item, yyDollar[3].node, yyDollar[5].item)
		}
	case 99:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:488
		{
			yyVAL.node = yylex.(*parser).newIndexExpr(yyDollar[1].node, yyDollar[2].item, yyDollar[4].node, yyDollar[6].item)
		}
	case 100:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:493
		{
			yyVAL.node = yylex.(*parser).newIndexExpr(nil, yyDollar[2].item, yyDollar[4].node, yyDollar[6].item)
		}
	case 101:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:497
		{
			yyVAL.node = yylex.(*parser).newIndexExpr(yyDollar[1].node, yyDollar[2].item, yyDollar[4].node, yyDollar[6].item)
		}
	case 102:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:501
		{
			yyVAL.node = yylex.(*parser).newIndexExpr(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].item)
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:510
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:514
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:518
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:522
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:526
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:530
		{
			yyVAL.node = yylex.(*parser).newAttrExpr(yyDollar[1].node, yyDollar[3].node)
		}
	case 109:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:537
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[3].node, yyDollar[5].node, yyDollar[2].item, yyDollar[6].item)
		}
	case 110:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:541
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node, yyDollar[2].item, yyDollar[8].item)
		}
	case 111:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:545
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[3].node, yyDollar[5].node, yyDollar[2].item, yyDollar[6].item)
		}
	case 112:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:549
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node, yyDollar[2].item, yyDollar[8].item)
		}
	case 113:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:553
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[3].node, yyDollar[5].node, yyDollar[2].item, yyDollar[6].item)
		}
	case 114:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gram.y:557
		{
			yyVAL.node = yylex.(*parser).newSliceExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node, yyDollar[2].item, yyDollar[8].item)
		}
	case 115:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:563
		{
			yyVAL.node = yylex.(*parser).newListLiteralEnd(yyVAL.node, yyDollar[2].item.Pos)
		}
	case 116:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:567
		{
			yyVAL.node = yylex.(*parser).newListLiteralEnd(yyVAL.node, yyDollar[4].item.Pos)
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:571
		{
			yyVAL.node = yylex.(*parser).newListLiteralStart(yyDollar[1].item.Pos)
			yyVAL.node = yylex.(*parser).newListLiteralEnd(yyVAL.node, yyDollar[3].item.Pos)
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:578
		{
			yyVAL.node = yylex.(*parser).newListLiteralStart(yyDollar[1].item.Pos)
			yyVAL.node = yylex.(*parser).newListLiteralAppendExpr(yyVAL.node, yyDollar[3].node)
		}
	case 119:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:583
		{
			yyVAL.node = yylex.(*parser).newListLiteralAppendExpr(yyVAL.node, yyDollar[4].node)
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:591
		{
			yyVAL.node = yylex.(*parser).newMapLiteralEnd(yyVAL.node, yyDollar[3].item.Pos)
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:595
		{
			yyVAL.node = yylex.(*parser).newMapLiteralEnd(yyVAL.node, yyDollar[4].item.Pos)
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:599
		{
			yyVAL.node = yylex.(*parser).newMapLiteralStart(yyDollar[1].astblock.LBracePos.Pos)
			yyVAL.node = yylex.(*parser).newMapLiteralEnd(yyVAL.node, yyDollar[1].astblock.RBracePos.Pos)
		}
	case 124:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:606
		{
			yyVAL.node = yylex.(*parser).newMapLiteralStart(yyDollar[1].item.Pos)
			yyVAL.node = yylex.(*parser).newMapLiteralAppendExpr(yyVAL.node, yyDollar[3].node, yyDollar[6].node)
		}
	case 125:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gram.y:611
		{
			yyVAL.node = yylex.(*parser).newMapLiteralAppendExpr(yyDollar[1].node, yyDollar[4].node, yyDollar[7].node)
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:618
		{
			yyVAL.node = yylex.(*parser).newIdentifierLiteral(yyDollar[1].item)
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:622
		{
			yyDollar[1].item.Val = yylex.(*parser).unquoteString(yyDollar[1].item.Val)
			yyVAL.node = yylex.(*parser).newIdentifierLiteral(yyDollar[1].item)
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:629
		{
			yyVAL.node = yylex.(*parser).newNumberLiteral(yyDollar[1].item)
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:633
		{
			yyVAL.node = yylex.(*parser).newBoolLiteral(yyDollar[1].item.Pos, true)
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:637
		{
			yyVAL.node = yylex.(*parser).newBoolLiteral(yyDollar[1].item.Pos, false)
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:641
		{
			yyDollar[1].item.Val = yylex.(*parser).unquoteString(yyDollar[1].item.Val)
			yyVAL.node = yylex.(*parser).newStringLiteral(yyDollar[1].item)
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:646
		{
			yyDollar[1].item.Val = yylex.(*parser).unquoteMultilineString(yyDollar[1].item.Val)
			yyVAL.node = yylex.(*parser).newStringLiteral(yyDollar[1].item)
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:651
		{
			yyVAL.node = yylex.(*parser).newNilLiteral(yyDollar[1].item.Pos)
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:655
		{
			yyVAL.node = yylex.(*parser).newNilLiteral(yyDollar[1].item.Pos)
		}
	}
	goto yystack /* stack new state and value */
}
