name: ci 
on:
  push:
    branches:
      - master 
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-section-index mkdocs-static-i18n
      - run: mkdocs gh-deploy --force
